function getData(k){return JSON.parse(localStorage.getItem(k))||[]}function setData(k,v){localStorage.setItem(k,JSON.stringify(v))}
var students=getData("students"),teachers=getData("teachers"),fees=getData("fees"),groups=getData("groups"),sessions=getData("sessions"),attendance=getData("attendance");
function today(){return new Date().toISOString().slice(0,10)}
function esc(x){return String(x??"").replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}

function renderStudents(list){var t=document.querySelector("#studentsTable tbody");if(!t)return;t.innerHTML="";(list||students).forEach(function(s,i){var r=t.insertRow();[s.name,s.phone,s.parentPhone,s.grade,s.group,s.fees+" جنيه"].forEach(function(x){r.insertCell().innerHTML=esc(x)});r.insertCell().innerHTML="<button onclick='editStudent("+i+")'>✏️ تعديل</button> <button class='danger' onclick='deleteStudent("+i+")'>🗑️ حذف</button>"})}
var ab=document.getElementById("addStudent");if(ab)ab.onclick=function(){var s={name:studentName.value.trim(),phone:studentPhone.value.trim(),parentPhone:parentPhone.value.trim(),grade:studentGrade.value.trim(),group:studentGroup.value.trim(),fees:studentFees.value};if(!s.name||!s.phone||!s.parentPhone||!s.grade||!s.group||!s.fees)return alert("من فضلك اكتب كل البيانات");var ei=Number(ab.dataset.edit||-1);if(ei>=0){students[ei]=s;delete ab.dataset.edit;ab.innerHTML="💾 حفظ الطالب"}else students.push(s);setData("students",students);["studentName","studentPhone","parentPhone","studentGrade","studentGroup","studentFees"].forEach(function(id){document.getElementById(id).value=""});renderStudents();updateDashboard();alert("✅ تم الحفظ")}
function editStudent(i){var s=students[i];studentName.value=s.name;studentPhone.value=s.phone;parentPhone.value=s.parentPhone;studentGrade.value=s.grade;studentGroup.value=s.group;studentFees.value=s.fees;ab.dataset.edit=i;ab.innerHTML="✏️ حفظ التعديل";scrollTo({top:0,behavior:"smooth"})}
function deleteStudent(i){if(confirm("هل أنت متأكد من حذف الطالب؟")){students.splice(i,1);setData("students",students);renderStudents();updateDashboard()}}
var ss=document.getElementById("searchStudent");if(ss)ss.oninput=function(){var v=this.value.toLowerCase().trim();renderStudents(students.filter(function(s){return s.name.toLowerCase().includes(v)}))}

function renderTeachers(){var t=document.getElementById("teachersTable");if(!t)return;t.innerHTML="";teachers.forEach(function(x,i){var r=t.insertRow();[x.name,x.subject,x.phone].forEach(function(v){r.insertCell().innerHTML=esc(v)});r.insertCell().innerHTML="<button onclick='editTeacher("+i+")'>✏️ تعديل</button> <button class='danger' onclick='deleteTeacher("+i+")'>🗑️ حذف</button>"})}
var at=document.getElementById("addTeacher");if(at)at.onclick=function(){var x={name:teacherName.value.trim(),subject:teacherSubject.value.trim(),phone:teacherPhone.value.trim()};if(!x.name||!x.subject||!x.phone)return alert("من فضلك اكتب كل البيانات");var i=Number(at.dataset.edit||-1);if(i>=0){teachers[i]=x;delete at.dataset.edit;at.innerHTML="💾 حفظ المدرس"}else teachers.push(x);setData("teachers",teachers);teacherName.value=teacherSubject.value=teacherPhone.value="";renderTeachers();updateDashboard();alert("✅ تم الحفظ")}
function editTeacher(i){var x=teachers[i];teacherName.value=x.name;teacherSubject.value=x.subject;teacherPhone.value=x.phone;at.dataset.edit=i;at.innerHTML="✏️ حفظ التعديل";scrollTo({top:0,behavior:"smooth"})}
function deleteTeacher(i){if(confirm("هل أنت متأكد من حذف المدرس؟")){teachers.splice(i,1);setData("teachers",teachers);renderTeachers();updateDashboard()}}

function renderFees(){var t=document.getElementById("feesTable");if(!t)return;t.innerHTML="";fees.forEach(function(x,i){var r=t.insertRow();[x.student,x.amount+" جنيه",x.date].forEach(function(v){r.insertCell().innerHTML=esc(v)});r.insertCell().innerHTML="<button class='danger' onclick='deleteFee("+i+")'>🗑️ حذف</button>"})}
var af=document.getElementById("addFee");if(af)af.onclick=function(){var x={student:feeStudent.value.trim(),amount:feeAmount.value,date:feeDate.value||today()};if(!x.student||!x.amount)return alert("من فضلك اكتب الطالب والمبلغ");fees.push(x);setData("fees",fees);feeStudent.value=feeAmount.value="";renderFees();updateDashboard();alert("✅ تم تسجيل الدفعة")}
function deleteFee(i){if(confirm("هل أنت متأكد من حذف الدفعة؟")){fees.splice(i,1);setData("fees",fees);renderFees();updateDashboard()}}

function renderGroups(){var t=document.getElementById("groupsTable");if(!t)return;t.innerHTML="";groups.forEach(function(x,i){var r=t.insertRow();[x.name,x.teacher,x.subject,x.time].forEach(function(v){r.insertCell().innerHTML=esc(v)});r.insertCell().innerHTML="<button class='danger' onclick='deleteGroup("+i+")'>🗑️ حذف</button>"})}
var ag=document.getElementById("addGroup");if(ag)ag.onclick=function(){var x={name:groupName.value.trim(),teacher:groupTeacher.value.trim(),subject:groupSubject.value.trim(),time:groupTime.value.trim()};if(!x.name||!x.teacher||!x.subject||!x.time)return alert("من فضلك اكتب كل البيانات");groups.push(x);setData("groups",groups);groupName.value=groupTeacher.value=groupSubject.value=groupTime.value="";renderGroups();updateDashboard();alert("✅ تم حفظ المجموعة")}
function deleteGroup(i){if(confirm("حذف المجموعة؟")){groups.splice(i,1);setData("groups",groups);renderGroups();updateDashboard()}}

function renderSessions(){var t=document.getElementById("sessionsTable");if(!t)return;t.innerHTML="";sessions.forEach(function(x,i){var r=t.insertRow();[x.group,x.teacher,x.subject,x.date,x.time].forEach(function(v){r.insertCell().innerHTML=esc(v)});r.insertCell().innerHTML="<button class='danger' onclick='deleteSession("+i+")'>🗑️ حذف</button>"})}
var ac=document.getElementById("addSession");if(ac)ac.onclick=function(){var x={group:sessionGroup.value.trim(),teacher:sessionTeacher.value.trim(),subject:sessionSubject.value.trim(),date:sessionDate.value,time:sessionTime.value};if(!x.group||!x.teacher||!x.subject||!x.date||!x.time)return alert("من فضلك اكتب كل البيانات");sessions.push(x);setData("sessions",sessions);sessionGroup.value=sessionTeacher.value=sessionSubject.value=sessionDate.value=sessionTime.value="";renderSessions();alert("✅ تم حفظ الحصة")}
function deleteSession(i){if(confirm("حذف الحصة؟")){sessions.splice(i,1);setData("sessions",sessions);renderSessions()}}

function renderAttendance(){var t=document.getElementById("attendanceTable");if(!t)return;t.innerHTML="";attendance.forEach(function(x,i){var r=t.insertRow();r.insertCell().innerHTML=esc(x.student);r.insertCell().innerHTML="<span class='"+(x.status=="حاضر"?"status-present":"status-absent")+"'>"+esc(x.status)+"</span>";r.insertCell().innerHTML=esc(x.date);r.insertCell().innerHTML="<button class='danger' onclick='deleteAttendance("+i+")'>🗑️ حذف</button>"})}
var aa=document.getElementById("addAttendance");if(aa)aa.onclick=function(){var x={student:attendanceStudent.value.trim(),status:attendanceStatus.value,date:attendanceDate.value||today()};if(!x.student)return alert("اكتب اسم الطالب");attendance.push(x);setData("attendance",attendance);attendanceStudent.value="";attendanceDate.value="";renderAttendance();updateDashboard();alert("✅ تم التسجيل")}
function deleteAttendance(i){if(confirm("حذف السجل؟")){attendance.splice(i,1);setData("attendance",attendance);renderAttendance();updateDashboard()}}

function updateDashboard(){var s=document.getElementById("studentsCount"),t=document.getElementById("teachersCount"),g=document.getElementById("groupsCount"),p=document.getElementById("paymentsTotal");if(s)s.innerHTML=students.length;if(t)t.innerHTML=teachers.length;if(g)g.innerHTML=groups.length;if(p)p.innerHTML=fees.reduce(function(a,x){return a+Number(x.amount||0)},0);var ro=document.getElementById("recentOperations");if(ro&&fees.length){ro.innerHTML="آخر دفعة: "+esc(fees[fees.length-1].student)+" — "+esc(fees[fees.length-1].amount)+" جنيه"}}
function reports(){if(!document.getElementById("reportStudents"))return;reportStudents.innerHTML=students.length;reportTeachers.innerHTML=teachers.length;reportGroups.innerHTML=groups.length;reportFees.innerHTML=fees.reduce(function(a,x){return a+Number(x.amount||0)},0)+" جنيه";reportPresent.innerHTML=attendance.filter(function(x){return x.status=="حاضر"}).length;reportAbsent.innerHTML=attendance.filter(function(x){return x.status=="غائب"}).length;reportSummary.innerHTML="إجمالي الطلاب "+students.length+"، والمدرسين "+teachers.length+"، والمجموعات "+groups.length+"، وإجمالي المدفوعات "+fees.reduce(function(a,x){return a+Number(x.amount||0)},0)+" جنيه."}
var saveSet=document.getElementById("saveSettings");if(saveSet)saveSet.onclick=function(){localStorage.setItem("centerName",centerName.value);localStorage.setItem("adminName",adminName.value);alert("✅ تم حفظ الإعدادات")}
var clear=document.getElementById("clearData");if(clear)clear.onclick=function(){if(confirm("سيتم حذف جميع بيانات النظام من هذا الجهاز. هل أنت متأكد؟")){["students","teachers","fees","groups","sessions","attendance"].forEach(function(k){localStorage.removeItem(k)});location.reload()}}
renderStudents();renderTeachers();renderFees();renderGroups();renderSessions();renderAttendance();updateDashboard();reports();
